name: campus_traveller
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.4
  cupertino_icons: ^1.0.2
  firebase_app_check: ^0.0.6+3
  firebase_auth: ^3.3.4
  firebase_core: ^1.10.5
  firebase_messaging: ^11.2.4
  firebase_storage: ^10.2.4
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.1.5
  flutter_native_image: ^0.0.6+1
  get_it: ^7.2.0
  google_maps_flutter: ^2.1.1
  http: ^0.13.4
  image_picker: ^0.8.4+4
  intl: ^0.17.0
  path: ^1.8.0
  path_provider: ^2.0.8
  permission_handler: ^8.3.0
  proste_bezier_curve: ^2.0.2
  provider: ^6.0.1
  sliding_up_panel: ^2.0.0+1
  webview_flutter: ^3.0.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
